import { describe, expect, it } from "vitest";
import { auditMediaAsset } from "./audit.js";

describe("auditMediaAsset — FTC disclosure gate", () => {
  it("passes a clean, concrete prompt with a real AI disclosure", () => {
    const r = auditMediaAsset({
      prompt: "A weekly grocery pantry on a wooden kitchen counter, natural window light, top-down.",
      caption: "Snap a receipt, watch your pantry fill in.",
      disclosure: "Image created with AI assistance.",
    });
    expect(r.pass).toBe(true);
    expect(r.violations).toHaveLength(0);
  });

  it("rejects a missing disclosure (FTC requires one)", () => {
    const r = auditMediaAsset({ prompt: "A tidy pantry shelf, soft daylight." });
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.kind === "missing-disclosure")).toBe(true);
  });

  it("rejects a disclosure that does not convey AI involvement", () => {
    const r = auditMediaAsset({
      prompt: "A tidy pantry shelf, soft daylight.",
      disclosure: "Made in our studio.",
    });
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.kind === "weak-disclosure")).toBe(true);
  });

  it("accepts several disclosure phrasings that convey AI", () => {
    for (const disclosure of [
      "AI-generated image",
      "Synthetic media, AI-assisted",
      "This asset was generated by AI.",
    ]) {
      const r = auditMediaAsset({ prompt: "A pantry shelf in daylight.", disclosure });
      expect(r.pass).toBe(true);
    }
  });
});

describe("auditMediaAsset — not-obviously-AI slop gate", () => {
  it("rejects a prompt reaching for obvious-AI slop vocabulary", () => {
    const r = auditMediaAsset({
      prompt: "hyper-realistic 8k octane render of a pantry, vibrant colors, cinematic lighting",
      disclosure: "AI-generated.",
    });
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.kind === "slop-prompt")).toBe(true);
  });

  it("also inspects the shipping caption for slop", () => {
    const r = auditMediaAsset({
      prompt: "A pantry shelf in daylight.",
      caption: "Trending on ArtStation, award-winning kitchen vibes!",
      disclosure: "AI-generated.",
    });
    expect(r.pass).toBe(false);
    expect(r.violations.some((v) => v.kind === "slop-prompt")).toBe(true);
  });

  it("is case-insensitive on slop matching", () => {
    const r = auditMediaAsset({
      prompt: "A PHOTOREALISTIC RENDER of shelves",
      disclosure: "AI-generated.",
    });
    expect(r.pass).toBe(false);
  });

  it("reports every violation at once (disclosure + slop)", () => {
    const r = auditMediaAsset({ prompt: "ultra-realistic rainbow gradient background" });
    expect(r.pass).toBe(false);
    expect(r.violations.length).toBeGreaterThanOrEqual(2);
  });
});
